### ISSUE TITLE
Roadmap v3 / PHPUnit 11

### ISSUE THREAD

**Issue by jrfnl** [Yoast/PHPUnit-Polyfills#152]
PHPUnit 11 has just been released.

As this is a major release with breaking changes, upgrading should be a done deliberately and managed.
This effectively means that upgrading to a PHPUnit Polyfills version which supports PHPUnit 11 should also be done deliberately and managed, so the Polyfills should get a new major release. 

The intention is for the `1.x` series and `2.x` series to continue to be maintained, for as long as [PHPUnit continues to make PHPUnit 9.x/10.x compatible with new PHP versions](https://phpunit.de/supported-versions.html).

Refs:
* https://phpunit.de/announcements/phpunit-11.html
* https://github.com/sebastianbergmann/phpunit/blob/main/ChangeLog-11.0.md

## Proposed Roadmap for PHPUnit Polyfills 3.0 / PHPUnit 11.0 support

- [x] Update README links in the 2.x branch to point to the PHPUnit 10 manual. - PR #190
- [x] Add a `3.x` branch.
    - [x] Add branch protection rules for the 3.x branch
- [x] Drop support for PHPUnit < 6.4 / PHP < 7.0. - PRs #192 + #193
- [x] Verify if the visibility of available methods needs to be updated. See sebastianbergmann/phpunit#5213 - PR #197
- [x] Remove the [`AssertAttributeHelper`](https://github.com/Yoast/PHPUnit-Polyfills#yoastphpunitpolyfillshelpersassertattributehelper) which was only intended to buy people a little more time to upgrade to PHPUnit 9.x. - PR #194
- [x] Add a new polyfill for the new `expectUserDeprecationMessage()` and `expectUserDeprecationMessageMatches()` methods. See sebastianbergmann/phpunit#5605 - PR #200
- [x] Add a new polyfill for the new `assertArrayIs*ToArray*ListOfKeys()` assertions. See sebastianbergmann/phpunit#5600 - PR #198
- [x] Add a new polyfill for the new PHPUnit 11.2+ `assertObjectNotEquals()` assertion. See sebastianbergmann/phpunit#5811 - PR #199
- [x] Verify the documentation is in line with the changes. PR #203
- [x] Allow PHPUnit 11.x. - PR #196

## Request for comments

This roadmap is open for comments.
