### ISSUE TITLE
Roadmap v2 / PHPUnit 10

### ISSUE THREAD

**Issue by jrfnl** [Yoast/PHPUnit-Polyfills#95]
PHPUnit 10 has been released beginning of February.

As this is a major release with breaking changes, upgrading should be a done deliberately and managed.
This effectively means that upgrading to a PHPUnit Polyfills version which supports PHPUnit 10 should also be done deliberately and managed, so the Polyfills should get a new major release. 

To this end, the `develop` branch in this repo will be renamed to `1.x` and a new `2.x` branch will be added to contain the code for the `2.x` series.

The intention is for the `1.x` series to continue to be maintained, alongside the `2.x` series, for as long as [PHPUnit continues to make PHPUnit 9.x compatible with new PHP versions](https://phpunit.de/supported-versions.html).

Refs:
* https://phpunit.de/announcements/phpunit-10.html
* https://github.com/sebastianbergmann/phpunit/blob/main/ChangeLog-10.0.md

## Proposed Roadmap for PHPUnit Polyfills 2.0 / PHPUnit 10.0 support

- [x] Rename the `develop` branch to `1.x` and add a `2.x` branch.
- [x] Drop support for PHPUnit < 5.7 / PHP < 5.6. - PR #102
- [x] Make all assertion methods in the public API `final` (following in PHPUnit's footsteps). PR #104
- [ ] Remove the [`AssertAttributeHelper`](https://github.com/Yoast/PHPUnit-Polyfills#yoastphpunitpolyfillshelpersassertattributehelper) which was only intended to buy people a little more time to upgrade to PHPUnit 9.x.
    **Open question**: should the `AssertAttributeHelper` still remain for the time being ? And if so, for how long ?
- [x] Remove the [`ExpectPHPException`](https://github.com/Yoast/PHPUnit-Polyfills#phpunit--840-yoastphpunitpolyfillspolyfillsexpectphpexception) Polyfill as this is functionality no longer supported in PHPUnit 10.0. - PR #108
    I wouldn't be adverse to adding a `PHPErrorHelper` class/trait for the time being to buy people a little more time though (which similar to the `AssertAttributeHelper` would still require test code changes to use, so people will still have to evaluate the tests which use(d) this functionality).
- [x] Add a new polyfill for the new `assertStringEqualsStringIgnoringLineEndings()` and `assertStringContainsStringIgnoringLineEndings()` assertions. - PR #109
- [x] Add a new polyfill for the new `assertIsList()` assertion. - PR #110
- [x] Add a new polyfill for the new PHPUnit 10.1 `assertObject[Not]HasProperty()` assertions. - PR #116
- [ ] Handle the change from TestListener to Event system for the TestListener Polyfill.
- [x] Verify the documentation is in line with the changes.
- [x] Allow PHPUnit 10.x. - PR #130

## Planning

Providing I manage to get everything working, release version 2.x before the end of March 2023.

## Request for comments

This roadmap is open for comments and I'd especially like to hear opinions on the `AssertAttributeHelper` and about a potential `PHPErrorHelper`.

**Comment by jrfnl** [comment]
Nearly there.... just some final touches needed for the test listener implementation.

Also, looks like PHPUnit 10.1 (expected mid-April) is introducing two new assertions [assertObjectHasProperty() and assertObjectNotHasProperty()](https://github.com/sebastianbergmann/phpunit/pull/5231), so would be good to get those polyfilled as well.

**Comment by jrfnl** [comment]
Closing as [version 2.0.0](https://github.com/Yoast/PHPUnit-Polyfills/releases/tag/2.0.0) has been released.

A separate ticket is now open to track the PHPUnit 10 TestListener implementation: #128.
